name: Build API Reference docs using sphinx 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

env:
  POETRY_VERSION: "1.6.1"
  PYTHON_VERSION: "3.10"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get code 
        uses: actions/checkout@v3
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: install poetry 
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}

      - name: Install dependencies 
        run: make install-sphinx-deps
      
      - name: Build API documentation
        run: |
          poetry run make apidocs